#!/bin/bash

if [ "$1" = "--dev" ]; then

  echo '[info] running in dev mode (sass server is running)'

  if ! ps aux | grep sass | grep -v 'grep sass'; then
    /usr/local/bin/sass --watch ./assets/static/css/main.scss:./assets/static/css/main.css &
    SASS_PID=$!
    echo "[info] starting sass server. PID is: $SASS_PID"
  else
    echo '[info] sass is already running'
  fi

else
  echo '[info] running in user mode'
fi

function kill_sass {
  if [ ! -z $SASS_PID ]; then
    echo "[info] killing sass server with PID: $SASS_PID ... "
    kill -9 $SASS_PID
  else
    echo "nothing to clean up, sass not running"
  fi

}

trap kill_sass SIGINT

lektor server --prune -h 0.0.0.0 -v
