#!/bin/bash

# see this for starting/stopping sass process: https://superuser.com/questions/330520/kill-background-processes-started-by-bash-script


echo "arg: $1"

if [ "$1" = "--dev" ]; then

  echo '[info] running in dev mode (sass server is running)'

  if ! ps aux | grep sass | grep -v 'grep sass'; then
    echo '[info] starting sass'
    /usr/local/bin/sass --watch ./assets/static/css/main.scss:./assets/static/css/main.css &
  else
    echo '[info] sass is already running'
  fi

else
  echo '[info] running in user mode'
fi


lektor server --prune -h 0.0.0.0 -v
